# Generated by Django 5.1.6 on 2025-02-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linked_student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
